### ISSUE TITLE
[BUG] - l4d2_tank_hp 生成的坦克血量不正确

### ISSUE THREAD

**Issue by PencilMario** [darkmjk/l4d2_plugins_coop#1]
在部分情况下，路程克/连续刷克的第一只克的血量总是为4000

**复现方式：**

使用all4dead生成坦克，第一只tank只有4000hp，第二只和后续的tank则为8000hp（普通/专家难度一致，1玩家3生还bot）    
所有坦克死亡后，再次重新生成，第一只tank仍然只有4000hp    
也许可能是因为插件冲突的问题，我没针对测试

**解决办法？：**
我在我自己的服用timer重新改了这部分代码，目前可以正常工作    

https://github.com/PencilMario/L4D2-Not0721Here-CoopSvPlugins/blob/239aebc07f9ccad714ebd2d48ee2161fa38ee4c7/addons/sourcemod/scripting/l4d2_tank_hp.sp#L145-L185

**Comment by NanakaNeko** [comment]
感谢反馈。不过该插件并不是我写的，主要是豆瓣酱开发，我只是配合伤害插件略作提示修改。至于血量问题应该是上次求生更新后出现的，具体原因我也不清楚，我这里偶现过。
