### ISSUE TITLE
shop.sp

### ISSUE THREAD

**Issue by txuk1x** [darkmjk/l4d2_plugins_coop#3]
大佬你好，能否在shop的个人信息中添加一个在本服的游戏时长的记录？如果麻烦，能不能提供一下大致的思路，非常感谢！

**Comment by NanakaNeko** [comment]
在过关时候使用GetClientTime()获取时间，或者使用GetEngineTime()在加入退出服务器做差，然后每次存取时间累加。不过我并不太推荐在sqlite数据库记录，丢失数据概率太大，想要正经记录数据建议使用MySQL。

**Comment by NanakaNeko** [comment]
最新插件已经加了。sqlite容易丢数据，所以建议还是用MySQL统计数据。

**Comment by txuk1x** [comment]
感谢大佬！

**Comment by txuk1x** [comment]
大佬你好，是否应该在回合结束阶段才将rank总数据写入？这样应该会缓解如喷子黑枪和土质炸一群小怪的时候会造成卡顿

**Comment by NanakaNeko** [comment]
> 大佬你好，是否应该在回合结束阶段才将rank总数据写入？这样应该会缓解如喷子黑枪和土质炸一群小怪的时候会造成卡顿

已经更改
