### ISSUE TITLE
music插件的一点小问题

### ISSUE THREAD

**Issue by Majestymo** [darkmjk/l4d2_plugins_coop#4]
在安全区播放音乐时有报错，代码如下
12/30/2023 - 18:14:37: [SM] Exception reported: Client index 0 is invalid
L 12/30/2023 - 18:14:37: [SM] Blaming: optional/music.smx
L 12/30/2023 - 18:14:37: [SM] Call stack trace:
L 12/30/2023 - 18:14:37: [SM]   [0] PrintToChat
L 12/30/2023 - 18:14:37: [SM]   [1] Line 138, music.sp::PlayMusicDetail
L 12/30/2023 - 18:18:25: Error log file session closed.
另外在使用暂停插件时听歌，进行操作会导致歌曲无法终止，具体原因不清楚
插件链接
https://forums.alliedmods.net/showthread.php?p=1295519

**Comment by NanakaNeko** [comment]
> 在安全区播放音乐时有报错，代码如下 12/30/2023 - 18:14:37: [SM] Exception reported: Client index 0 is invalid L 12/30/2023 - 18:14:37: [SM] Blaming: optional/music.smx L 12/30/2023 - 18:14:37: [SM] Call stack trace: L 12/30/2023 - 18:14:37: [SM] [0] PrintToChat L 12/30/2023 - 18:14:37: [SM] [1] Line 138, music.sp::PlayMusicDetail L 12/30/2023 - 18:18:25: Error log file session closed. 另外在使用暂停插件时听歌，进行操作会导致歌曲无法终止，具体原因不清楚 插件链接 https://forums.alliedmods.net/showthread.php?p=1295519

报错原因是通报服务端错误，正常来讲选择播放音乐的都是玩家，不会是服务端。
暂停插件hook了聊天框和声音，暂停不了正常。

**Comment by Majestymo** [comment]
但是我是输入在客户端输入指令点歌的，为什么服务端会放歌😭

**Comment by NanakaNeko** [comment]
> 但是我是输入在客户端输入指令点歌的，为什么服务端会放歌😭

增加了强制关闭音乐指令，离开安全区域没有关闭的话，管理员可以强制关闭

**Comment by Majestymo** [comment]
pr了
