### ISSUE TITLE
大佬您的插件好像有点问题，没办法生效

### ISSUE THREAD

**Issue by Wanghaiqin123456** [darkmjk/l4d2_plugins_coop#6]
那个notify插件我无论怎么尝试都没办法生效，是不是有必须的前置插件我没安装啊，求解答

**Comment by NanakaNeko** [comment]
> 那个notify插件我无论怎么尝试都没办法生效，是不是有必须的前置插件我没安装啊，求解答

默认版本是需要商店插件，如果不想要商店，可以下载另一个去除依赖版本
readme已经更新
